import Joi from "joi";

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid("development", "production", "test").default("development"),
  PORT: Joi.number().default(3000),
  WEB_ORIGIN: Joi.string().default("http://localhost:5173"),
  JWT_SECRET: Joi.string().min(16).required(),
  JWT_REFRESH_SECRET: Joi.string().min(16).required(),
  JWT_EXPIRES_IN: Joi.string().default("15m"),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default("7d"),
  JWT_ISSUER: Joi.string().default("chronoatlas"),
  JWT_AUDIENCE: Joi.string().default("chronoatlas-web"),
  EMAIL_VERIFY_TTL_MINUTES: Joi.number().default(1440),
  PASSWORD_RESET_TTL_MINUTES: Joi.number().default(30),
  CSRF_COOKIE_NAME: Joi.string().default("csrf_token"),
  RATE_LIMIT_TTL: Joi.number().default(60),
  RATE_LIMIT_LIMIT: Joi.number().default(30),
  MAIL_DEV_OUTPUT: Joi.string().valid("log", "file", "off").default("log"),
  MAIL_DEV_DIR: Joi.string().default("mail_outbox"),
  APP_URL: Joi.string().default("http://localhost:5173"),
  BOOTSTRAP_ADMIN_EMAIL: Joi.string().default("admin@chronoatlas.local"),
  BOOTSTRAP_ADMIN_PASSWORD: Joi.string().default("admin123"),
  BOOTSTRAP_ADMIN_NAME: Joi.string().default("管理员"),
  PG_HOST: Joi.string().required(),
  PG_PORT: Joi.number().default(5432),
  PG_USER: Joi.string().required(),
  PG_PASSWORD: Joi.string().required(),
  PG_DATABASE: Joi.string().required(),
  PG_SSL: Joi.string().default("false"),
  PG_SCHEMA: Joi.string().default("public"),
  PG_TABLE: Joi.string().default("app_data")
});
